DROP TABLE IF EXISTS SC_GROUP;
DROP TABLE IF EXISTS STUDENT_CLASS;
DROP TABLE IF EXISTS _GROUP;
DROP TABLE IF EXISTS PROGRAMME_COURSE;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS CLASS_TEACHER;
DROP TABLE IF EXISTS PROGRAMME;
DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	UNAME VARCHAR(256) NOT NULL,
	EMAIL VARCHAR(256),
	PRIMARY KEY(EMAIL)
);

CREATE TABLE TEACHER(
	EMAIL VARCHAR(256),
	NUMBER INT,
	PRIMARY KEY (NUMBER),
	FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL) ON UPDATE CASCADE
);

CREATE TABLE COURSE(
	CNAME VARCHAR(128) UNIQUE,
	ACRONYM VARCHAR(5),
	COORDINATORNUMBER INT,
	PRIMARY KEY (ACRONYM),
	FOREIGN KEY (COORDINATORNUMBER) REFERENCES TEACHER(NUMBER) ON UPDATE CASCADE
);

CREATE TABLE CLASS(
	IDENTIFIER VARCHAR(5),
	SEMESTER_REPRESENT VARCHAR(5),
	COURSE_ACRONYM VARCHAR(5),
	PRIMARY KEY (IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM),
	FOREIGN KEY (COURSE_ACRONYM) REFERENCES COURSE(ACRONYM) ON UPDATE CASCADE
);

CREATE TABLE PROGRAMME(
	PROGRAMME_ID VARCHAR(10),
	PNAME VARCHAR(256) UNIQUE ,
	NUMBEROFSEMESTERS INT,
	PRIMARY KEY(PROGRAMME_ID)
);

CREATE TABLE STUDENT(
	EMAIL VARCHAR(256),
	NUMBER INT,
	PROGRAMME_ID VARCHAR(10),
	PRIMARY KEY(NUMBER),
	FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)ON UPDATE CASCADE,
	FOREIGN KEY(PROGRAMME_ID) REFERENCES PROGRAMME(PROGRAMME_ID) ON UPDATE CASCADE
);

CREATE TABLE CLASS_TEACHER (
	TEACHERNUMBER INT,
	C_ACRONYM VARCHAR(5),
	IDENTIFIERCLASS VARCHAR(5),
	SEMESTER_REPRESENT VARCHAR(5),
	PRIMARY KEY (TEACHERNUMBER,C_ACRONYM,IDENTIFIERCLASS,SEMESTER_REPRESENT),
	FOREIGN KEY (TEACHERNUMBER) REFERENCES TEACHER(NUMBER) ON UPDATE CASCADE,
	FOREIGN KEY (IDENTIFIERCLASS,SEMESTER_REPRESENT,C_ACRONYM) REFERENCES CLASS(IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM) ON UPDATE CASCADE
);

CREATE TABLE PROGRAMME_COURSE (
	PROGRAMME_ID VARCHAR(10),
	COURSEACRONYM VARCHAR(5),
	MANDATORY BOOLEAN NOT NULL,
	CURRICULARSEMESTER VARCHAR(20),
	PRIMARY KEY (PROGRAMME_ID,COURSEACRONYM,MANDATORY,CURRICULARSEMESTER),
	FOREIGN KEY (PROGRAMME_ID) REFERENCES PROGRAMME(PROGRAMME_ID) ON UPDATE CASCADE,
	FOREIGN KEY (COURSEACRONYM) REFERENCES COURSE(ACRONYM) ON UPDATE CASCADE
);

CREATE TABLE _GROUP (
    GROUP_NUMBER INT,
    PRIMARY KEY(GROUP_NUMBER)
);

CREATE TABLE STUDENT_CLASS (
    STUDENT_NUMBER INT,
    CLASS_IDENTIFIER VARCHAR(5),
    SEMESTER_REPRESENT VARCHAR(5),
    COURSE_ACRONYM VARCHAR(5),
    PRIMARY KEY(STUDENT_NUMBER, CLASS_IDENTIFIER, SEMESTER_REPRESENT, COURSE_ACRONYM),
    FOREIGN KEY(STUDENT_NUMBER) REFERENCES STUDENT(NUMBER) ON UPDATE CASCADE,
    FOREIGN KEY(CLASS_IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM) REFERENCES CLASS(IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM) ON UPDATE CASCADE
);

CREATE TABLE SC_GROUP(
	STUDENT_NUMBER INT,
    CLASS_IDENTIFIER VARCHAR(5),
    SEMESTER_REPRESENT VARCHAR(5),
    COURSE_ACRONYM VARCHAR(5),
	GROUP_NUMBER INT,
	
	PRIMARY KEY (STUDENT_NUMBER, CLASS_IDENTIFIER, SEMESTER_REPRESENT, COURSE_ACRONYM),
	FOREIGN KEY (STUDENT_NUMBER,CLASS_IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM) REFERENCES STUDENT_CLASS(STUDENT_NUMBER,CLASS_IDENTIFIER,SEMESTER_REPRESENT,COURSE_ACRONYM) ON UPDATE CASCADE,
    FOREIGN KEY (GROUP_NUMBER) REFERENCES _GROUP(GROUP_NUMBER) ON UPDATE CASCADE
);

INSERT INTO USERS VALUES ('João','joao@isel.pt');
INSERT INTO USERS VALUES ('Pedro', 'pedro@isel.pt');
INSERT INTO USERS VALUES ('Zé Artur','zeartur@isel.pt');
INSERT INTO USERS VALUES ('Jéssica','jessica@isel.pt');
INSERT INTO USERS VALUES ('Diogo','diogo@isel.pt');
INSERT INTO USERS VALUES ('Rita','rita@isel.pt');
INSERT INTO USERS VALUES ('Joana','joana@isel.pt');

INSERT INTO TEACHER VALUES ('joao@isel.pt',21);
INSERT INTO TEACHER VALUES ('zeartur@isel.pt',22);



INSERT INTO COURSE VALUES ('Laboratório de Software','LS',21);
INSERT INTO COURSE VALUES ('Arquitetura de Computadores','AC',22);
INSERT INTO COURSE VALUES ('Lógica e Sistemas Digitais','LSD',22);

INSERT INTO CLASS VALUES ('41D','1718W','LS');
INSERT INTO CLASS VALUES ('22D','1718W','AC');
INSERT INTO CLASS VALUES ('22D','1718W','LSD');

INSERT INTO PROGRAMME VALUES ('LEIC','LICENCIATURA ENGENHARIA INFORMATICA E COMPUTADORES',6);

INSERT INTO STUDENT VALUES ('pedro@isel.pt', 44781,'LEIC');
INSERT INTO STUDENT VALUES ('jessica@isel.pt',44820,'LEIC');
INSERT INTO STUDENT VALUES ('joana@isel.pt',43333,'LEIC');
INSERT INTO STUDENT VALUES ('diogo@isel.pt',44815,'LEIC');
INSERT INTO STUDENT VALUES ('rita@isel.pt',41212,'LEIC');


INSERT INTO CLASS_TEACHER VALUES (21,'LS', '41D','1718W');
INSERT INTO CLASS_TEACHER VALUES (22,'AC', '22D','1718W');

INSERT INTO PROGRAMME_COURSE VALUES ('LEIC','LS',true,'4');	

INSERT INTO _GROUP VALUES (1);
INSERT INTO _GROUP VALUES (2);

INSERT INTO STUDENT_CLASS VALUES (44781, '41D', '1718W', 'LS');
INSERT INTO STUDENT_CLASS VALUES (44820, '41D', '1718W', 'LS');
INSERT INTO STUDENT_CLASS VALUES (43333, '41D', '1718W', 'LS');
INSERT INTO STUDENT_CLASS VALUES (44815, '41D', '1718W', 'LS');


INSERT INTO SC_GROUP VALUES (44781, '41D', '1718W', 'LS', 1);
INSERT INTO SC_GROUP VALUES (44820, '41D', '1718W', 'LS', 1);




